// Editorial evidence snapshot. Review dates are not announcement or deployment dates.
import { bi, type Bilingual } from "./amd-ecosystem";

export const REVIEWED = "2026-09-24";
export const RESEARCH_PATH = "/research/nvidia-ai-ecosystem";
export const LAYERS = ["chips", "networking", "systems", "software", "cloud"] as const;
export const RELATIONS = ["supplier", "customer", "partner"] as const;
export const STAGES = ["shipped", "announced"] as const;
export type Layer = typeof LAYERS[number];
export type Relation = typeof RELATIONS[number];
export type Stage = typeof STAGES[number];

export const layerNames: Record<Layer, Bilingual> = {
  chips: bi("Chips and memory", "芯片与内存"),
  networking: bi("Networking", "网络"),
  systems: bi("Systems", "系统"),
  software: bi("Software / CUDA", "软件 / CUDA"),
  cloud: bi("Cloud and customers", "云与客户"),
};
export const relationNames: Record<Relation, Bilingual> = { supplier: bi("Supplier", "供应商"), customer: bi("Customer / deployer", "客户 / 部署方"), partner: bi("System or technology partner", "系统或技术合作伙伴") };
export const stageNames: Record<Stage, Bilingual> = { shipped: bi("Shipped / in use", "已出货 / 已使用"), announced: bi("Announced / planned", "已宣布 / 计划中") };

const TEN_K = { source: "NVIDIA FY2026 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000021/nvda-20260125.htm", date: "2026-02-25" };
const Q2_FY27 = { source: "NVIDIA Q2 FY2027 results", url: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027", date: "2026-08-26" };
const RUBIN_CES = { source: "NVIDIA Rubin platform launch", url: "https://nvidianews.nvidia.com/news/rubin-platform-ai-supercomputer", date: "2026-01-05" };
const CFO_Q2_FY27 = { source: "NVIDIA Q2 FY2027 CFO commentary", url: "https://s201.q4cdn.com/141608511/files/doc_financials/2027/Q227/Q2FY27-CFO-Commentary.pdf", date: "2026-08-26" };
const CRWV_GB300 = { source: "CoreWeave first GB300 NVL72 deployment", url: "https://www.coreweave.com/news/coreweave-becomes-first-cloud-provider-to-deploy-nvidia-gb300-nvl72-platform", date: "2025-07-03" };
const CRWV_RUBIN_FIRST = { source: "CoreWeave first Vera Rubin NVL72 bring-up", url: "https://investors.coreweave.com/news/news-details/2026/CoreWeave-Completes-Industry-First-Bring-Up-and-Validation-of-NVIDIA-Vera-Rubin-NVL72/", date: "2026-06-01" };
const RUBIN_PRODUCTION = { source: "NVIDIA Vera Rubin full-production release", url: "https://nvidianews.nvidia.com/news/vera-rubin-full-production-agentic-ai-factory", date: "2026-05-31" };

export type Evidence = { source: string; url: string; date: string | null };
export type EcosystemCompany = { id: string; symbol: string | null; name: Bilingual; role: Bilingual };
// `id` is the company's map identifier. A null symbol means the company is not yet in the YouAnalyst directory.
export const researchCompanies: EcosystemCompany[] = [
  { id: "US:NVDA", symbol: "NVDA", name: bi("NVIDIA", "英伟达"), role: bi("GPUs, CPUs, NVLink and Spectrum-X networking, rack-scale systems and CUDA", "GPU、CPU、NVLink 与 Spectrum-X 网络、机架级系统与 CUDA") },
  { id: "US:TSM", symbol: "TSM", name: bi("TSMC", "台积电"), role: bi("Wafer foundry for NVIDIA, including Blackwell wafers in Arizona", "英伟达的晶圆代工厂，包括在亚利桑那生产的 Blackwell 晶圆") },
  { id: "KR:SK-HYNIX", symbol: null, name: bi("SK hynix", "SK 海力士"), role: bi("Memory supplier; multiyear memory partnership announced for Vera Rubin", "内存供应商；已宣布面向 Vera Rubin 的多年内存合作") },
  { id: "US:MU", symbol: "MU", name: bi("Micron", "美光科技"), role: bi("Memory supplier; HBM4 in volume production for Vera Rubin", "内存供应商；面向 Vera Rubin 的 HBM4 已大规模量产") },
  { id: "KR:SAMSUNG", symbol: null, name: bi("Samsung Electronics", "三星电子"), role: bi("Memory supplier and wafer foundry; HBM4 designed for Vera Rubin", "内存供应商与晶圆代工厂；HBM4 面向 Vera Rubin 设计") },
  { id: "US:DELL", symbol: "DELL", name: bi("Dell", "戴尔"), role: bi("Delivered the first GB300 NVL72 and Vera Rubin NVL72 racks to CoreWeave", "向 CoreWeave 交付首批 GB300 NVL72 与 Vera Rubin NVL72 机架") },
  { id: "US:CRWV", symbol: "CRWV", name: bi("CoreWeave", "CoreWeave"), role: bi("Neocloud that brought up the first Vera Rubin NVL72 racks", "率先启用 Vera Rubin NVL72 机架的新型云服务商") },
  { id: "US:MSFT", symbol: "MSFT", name: bi("Microsoft", "微软"), role: bi("Azure named by NVIDIA as running Vera Rubin racks", "英伟达披露 Azure 已运行 Vera Rubin 机架") },
  { id: "ORG:ANTHROPIC", symbol: null, name: bi("Anthropic", "Anthropic"), role: bi("Model lab with up to 1 GW of planned Grace Blackwell and Vera Rubin capacity", "计划使用最多 1 GW Grace Blackwell 与 Vera Rubin 算力的模型公司") },
];

// `edge` links to a map relationship only when its status agrees with `stage`: a shipped row must not open an
// ANNOUNCED or PLANNED_ADOPTER_OF edge, and an announced row must not open a DOCUMENTED one. Otherwise the row
// keeps `edge: null` and "Open in map" opens the company instead.
export type Connection = Evidence & { also?: Evidence[]; id: string; companyId: string; symbol: string | null; edge: string | null; layer: Layer; kind: Relation; stage: Stage; label: Bilingual; status: Bilingual; summary: Bilingual; limit: Bilingual };
export const researchConnections: Connection[] = [
  { id: "tsm-wafers", companyId: "US:TSM", symbol: "TSM", edge: "US:TSM__SUPPLIER_OF__US:NVDA", layer: "chips", kind: "supplier", stage: "shipped", label: bi("TSMC → NVIDIA · Wafers and CoWoS packaging", "台积电 → 英伟达 · 晶圆与 CoWoS 封装"), status: bi("Disclosed in annual report", "年报披露"), summary: bi("NVIDIA's 10-K names TSMC and Samsung as the foundries that produce its semiconductor wafers and says it uses CoWoS technology for semiconductor packaging.", "英伟达 10-K 将台积电和三星列为其半导体晶圆代工厂，并说明其采用 CoWoS 技术进行半导体封装。"), limit: bi("The filing establishes a manufacturing dependency. It does not disclose wafer volumes, how CoWoS capacity is split between suppliers, or contract terms.", "年报证明制造依赖关系，但未披露晶圆数量、CoWoS 产能在供应商间的分配或合同条款。"), ...TEN_K },
  { id: "tsm-arizona", companyId: "US:TSM", symbol: "TSM", edge: "US:TSM__SUPPLIER_OF__US:NVDA", layer: "chips", kind: "supplier", stage: "shipped", label: bi("TSMC Arizona · First US-made Blackwell wafer", "台积电亚利桑那 · 首片美国制造 Blackwell 晶圆"), status: bi("Wafers in volume production", "晶圆已量产"), summary: bi("NVIDIA said TSMC's Phoenix fab was producing Blackwell wafers in volume when it marked the first Blackwell wafer made in the US.", "英伟达在庆祝首片美国制造的 Blackwell 晶圆时表示，台积电凤凰城工厂已在量产 Blackwell 晶圆。"), limit: bi("The post concerns wafer fabrication only. It does not say where those wafers are packaged or what share of Blackwell supply comes from Arizona.", "该文只涉及晶圆制造，未说明这些晶圆在何处封装，也未说明亚利桑那产能占 Blackwell 供应的比例。"), source: "NVIDIA blog: first US Blackwell wafer", url: "https://blogs.nvidia.com/blog/tsmc-blackwell-manufacturing/", date: "2025-10-17" },
  { id: "memory-10k", companyId: "KR:SK-HYNIX", symbol: null, edge: null, layer: "chips", kind: "supplier", stage: "shipped", label: bi("SK hynix, Micron, Samsung → NVIDIA · Memory", "SK 海力士、美光、三星 → 英伟达 · 内存"), status: bi("Disclosed in annual report", "年报披露"), summary: bi("NVIDIA's 10-K says it purchases memory from SK hynix, Micron and Samsung.", "英伟达 10-K 表示其向 SK 海力士、美光和三星采购内存。"), limit: bi("The filing names suppliers but does not rank them, split purchases by HBM generation, or tie a supplier to a specific GPU.", "年报列出供应商，但未排序，未按 HBM 代际划分采购，也未将供应商对应到具体 GPU。"), ...TEN_K },
  { id: "hynix-partnership", companyId: "KR:SK-HYNIX", symbol: null, edge: null, layer: "chips", kind: "supplier", stage: "announced", label: bi("SK hynix · Multiyear memory partnership", "SK 海力士 · 多年内存合作"), status: bi("Partnership announced", "已宣布合作"), summary: bi("NVIDIA and SK hynix announced a multiyear partnership to co-develop memory for Vera Rubin, Vera CPUs, RTX Spark PCs and Jetson Thor. It supports supply of advanced memory.", "英伟达与 SK 海力士宣布多年合作，为 Vera Rubin、Vera CPU、RTX Spark PC 和 Jetson Thor 共同开发内存，并支持先进内存供应。"), limit: bi("The announcement does not disclose volumes, prices or a contract value. Figures in press coverage are not confirmed by this source.", "公告未披露数量、价格或合同金额；媒体报道中的金额未经本来源证实。"), source: "NVIDIA–SK hynix partnership release", url: "https://nvidianews.nvidia.com/news/sk-hynix-ai-factory", date: "2026-06-07" },
  { id: "mu-hbm4", companyId: "US:MU", symbol: "MU", edge: null, layer: "chips", kind: "supplier", stage: "shipped", label: bi("Micron → NVIDIA · HBM4 for Vera Rubin", "美光 → 英伟达 · 面向 Vera Rubin 的 HBM4"), status: bi("High-volume production", "大规模量产"), summary: bi("Micron announced high-volume production of 36GB 12-high HBM4 designed for NVIDIA Vera Rubin.", "美光宣布面向英伟达 Vera Rubin 设计的 36GB 12 层 HBM4 进入大规模量产。"), limit: bi("Production for a platform is not a disclosed share of NVIDIA's HBM purchases, and it does not establish exclusivity.", "为某平台量产不等于披露了在英伟达 HBM 采购中的份额，也不代表独家供应。"), source: "Micron HBM4 release", url: "https://investors.micron.com/news-releases/news-release-details/micron-high-volume-production-hbm4-designed-nvidia-vera-rubin", date: "2026-03-16" },
  { id: "mu-hbm3e-gb300", companyId: "US:MU", symbol: "MU", edge: "US:MU__SUPPLIER_OF__US:NVDA", layer: "chips", kind: "supplier", stage: "announced", label: bi("Micron · HBM3E 12H designed into Blackwell Ultra", "美光 · HBM3E 12H 集成于 Blackwell Ultra"), status: bi("Design-in announced", "已宣布设计导入"), summary: bi("Micron said its HBM3E 12H 36GB is designed into NVIDIA HGX B300 NVL16 and GB300 NVL72, and that its SOCAMM was developed with NVIDIA for GB300.", "美光表示其 HBM3E 12H 36GB 已设计导入英伟达 HGX B300 NVL16 与 GB300 NVL72，其 SOCAMM 与英伟达合作为 GB300 开发。"), limit: bi("A design-in announcement predates shipments and does not show volumes. Treat it as a design win, not as delivery evidence.", "设计导入公告早于出货，也未披露数量；应视为设计中标，而非交付证据。"), source: "Micron GTC 2025 release", url: "https://investors.micron.com/news-releases/news-release-details/micron-innovates-data-center-edge-nvidia", date: "2025-03-18" },
  { id: "samsung-hbm4", companyId: "KR:SAMSUNG", symbol: null, edge: null, layer: "chips", kind: "supplier", stage: "shipped", label: bi("Samsung · HBM4 for Vera Rubin", "三星 · 面向 Vera Rubin 的 HBM4"), status: bi("Mass production", "已量产"), summary: bi("Samsung said at NVIDIA GTC 2026 that its HBM4, designed for the Vera Rubin platform, is in mass production.", "三星在 NVIDIA GTC 2026 上表示，其面向 Vera Rubin 平台设计的 HBM4 已进入量产。"), limit: bi("Mass production for a platform does not disclose NVIDIA's purchase volumes or qualification status for each product.", "为平台量产并未披露英伟达的采购量或各产品的认证状态。"), source: "Samsung GTC 2026 release", url: "https://news.samsung.com/global/samsung-unveils-hbm4e-showcasing-comprehensive-ai-solutions-nvidia-partnership-and-vision-at-nvidia-gtc-2026", date: null },
  { id: "assembly-10k", companyId: "TW:HON-HAI", symbol: null, edge: null, layer: "systems", kind: "supplier", stage: "shipped", label: bi("Hon Hai (Foxconn), Wistron, Fabrinet · Assembly and test", "鸿海（富士康）、纬创、Fabrinet · 组装与测试"), status: bi("Disclosed in annual report", "年报披露"), summary: bi("NVIDIA's 10-K says contract manufacturers such as Hon Hai, Wistron and Fabrinet perform assembly, testing and packaging of its final products.", "英伟达 10-K 表示鸿海、纬创和 Fabrinet 等合约制造商为其最终产品提供组装、测试和封装。"), limit: bi("\"Such as\" means the list is not complete. It does not say which rack systems each manufacturer builds.", "“例如”表示名单并不完整，年报也未说明各厂商分别生产哪些机架系统。"), ...TEN_K },
  { id: "dell-rubin", companyId: "US:DELL", symbol: "DELL", edge: "US:DELL__INTEGRATES_TECHNOLOGY_FROM__US:NVDA", layer: "systems", kind: "partner", stage: "shipped", label: bi("Dell · First Vera Rubin NVL72 racks shipped", "戴尔 · 首批 Vera Rubin NVL72 机架已出货"), status: bi("Delivered to CoreWeave", "已交付 CoreWeave"), summary: bi("Dell said it was first to ship systems built on Vera Rubin, delivering PowerRack systems with PowerEdge XE9812 servers to CoreWeave.", "戴尔表示其率先出货基于 Vera Rubin 的系统，向 CoreWeave 交付搭载 PowerEdge XE9812 服务器的 PowerRack 系统。"), limit: bi("A first delivery is a milestone, not a disclosed volume. It does not show Dell's share of Vera Rubin systems.", "首批交付是里程碑，并非披露的数量，也不能说明戴尔在 Vera Rubin 系统中的份额。"), source: "Dell blog: first Vera Rubin systems", url: "https://www.dell.com/en-us/blog/dell-first-to-ship-systems-built-on-nvidia-vera-rubin-platform-to-coreweave/", date: "2026-06-01" },
  { id: "builders-rubin", companyId: "US:HPE", symbol: "HPE", edge: null, layer: "systems", kind: "partner", stage: "announced", label: bi("HPE, Supermicro, Lenovo, Foxconn and others · Vera Rubin builders", "慧与、超微、联想、富士康等 · Vera Rubin 系统厂商"), status: bi("Named as system builders", "被列为系统厂商"), summary: bi("NVIDIA listed Dell, HPE, Lenovo and Supermicro, as well as Foxconn, Quanta Cloud Technology, Wistron, Wiwynn and others, among system builders ramping Vera Rubin. It said production shipments start in fall 2026.", "英伟达将戴尔、慧与、联想、超微以及富士康、云达科技、纬创、纬颖等列为推进 Vera Rubin 的系统厂商，并表示量产出货将于 2026 年秋季开始。"), limit: bi("Being named in a launch list is not evidence that a given builder has shipped Vera Rubin systems.", "出现在发布名单中并不证明某家厂商已出货 Vera Rubin 系统。"), ...RUBIN_PRODUCTION },
  { id: "smci-rubin", companyId: "US:SMCI", symbol: "SMCI", edge: null, layer: "systems", kind: "partner", stage: "announced", label: bi("Supermicro · Named Vera Rubin builder", "超微 · 列名 Vera Rubin 系统厂商"), status: bi("Named as system builder", "被列为系统厂商"), summary: bi("Supermicro is one of the top system builders NVIDIA names for Vera Rubin.", "超微是英伟达为 Vera Rubin 列出的主要系统厂商之一。"), limit: bi("This does not establish shipped Vera Rubin systems or order sizes.", "这并不证明其已出货 Vera Rubin 系统，也未说明订单规模。"), ...RUBIN_PRODUCTION },
  { id: "crwv-rubin", companyId: "US:CRWV", symbol: "CRWV", edge: null, layer: "cloud", kind: "customer", stage: "shipped", label: bi("CoreWeave · Multi-rack Vera Rubin cluster", "CoreWeave · 多机架 Vera Rubin 集群"), status: bi("Operational per CoreWeave", "CoreWeave 称已投入运行"), summary: bi("CoreWeave announced a multi-rack Vera Rubin NVL72 cluster with hundreds of Rubin GPUs. It completed the first Vera Rubin NVL72 bring-up on June 1, 2026, and first deployed GB300 NVL72 on July 3, 2025.", "CoreWeave 宣布启用包含数百颗 Rubin GPU 的多机架 Vera Rubin NVL72 集群；其于 2026 年 6 月 1 日完成首台 Vera Rubin NVL72 启用，并于 2025 年 7 月 3 日首次部署 GB300 NVL72。"), limit: bi("Hundreds of GPUs is an early cluster, not CoreWeave's full Rubin fleet or committed spend with NVIDIA.", "数百颗 GPU 是早期集群，并不代表 CoreWeave 的全部 Rubin 规模或对英伟达的承诺支出。"), source: "CoreWeave multi-rack Vera Rubin release", url: "https://coreweave.com/news/coreweave-brings-up-multi-rack-nvidia-vera-rubin-nvl72-cluster", date: "2026-09-16", also: [CRWV_RUBIN_FIRST, CRWV_GB300] },
  { id: "msft-rubin", companyId: "US:MSFT", symbol: "MSFT", edge: null, layer: "cloud", kind: "customer", stage: "shipped", label: bi("Microsoft Azure · Vera Rubin racks running", "微软 Azure · Vera Rubin 机架已运行"), status: bi("Running per NVIDIA", "英伟达称已运行"), summary: bi("NVIDIA said Vera Rubin is ramping into full production with racks running at partners including CoreWeave, Google Cloud, Microsoft Azure, Oracle Cloud Infrastructure and Nebius.", "英伟达表示 Vera Rubin 正进入全面量产，机架已在 CoreWeave、Google Cloud、微软 Azure、甲骨文云和 Nebius 等合作伙伴处运行。"), limit: bi("Racks running is not general availability to customers, and NVIDIA does not disclose each cloud's volume.", "机架运行不等于已向客户全面开放，英伟达也未披露各云厂商的规模。"), ...Q2_FY27 },
  { id: "googl-rubin", companyId: "US:GOOGL", symbol: "GOOGL", edge: null, layer: "cloud", kind: "customer", stage: "shipped", label: bi("Google Cloud · Vera Rubin racks running", "Google Cloud · Vera Rubin 机架已运行"), status: bi("Running per NVIDIA", "英伟达称已运行"), summary: bi("Google Cloud is named in NVIDIA's Q2 FY2027 results among partners with Vera Rubin racks running.", "英伟达 2027 财年第二季度业绩将 Google Cloud 列为已运行 Vera Rubin 机架的合作伙伴。"), limit: bi("This does not show Google's volume, and Google also builds its own TPUs, so it is not an exclusive relationship.", "这并不说明谷歌的采购规模；谷歌也自研 TPU，双方并非排他关系。"), ...Q2_FY27 },
  { id: "orcl-rubin", companyId: "US:ORCL", symbol: "ORCL", edge: null, layer: "cloud", kind: "customer", stage: "shipped", label: bi("Oracle Cloud Infrastructure · Vera Rubin racks running", "甲骨文云 · Vera Rubin 机架已运行"), status: bi("Running per NVIDIA", "英伟达称已运行"), summary: bi("OCI is named in NVIDIA's Q2 FY2027 results among partners with Vera Rubin racks running.", "英伟达 2027 财年第二季度业绩将甲骨文云列为已运行 Vera Rubin 机架的合作伙伴。"), limit: bi("Racks running at a partner does not disclose order size or customer availability dates.", "合作伙伴处机架运行并未披露订单规模或客户可用日期。"), ...Q2_FY27 },
  { id: "nbis-rubin", companyId: "US:NBIS", symbol: "NBIS", edge: null, layer: "cloud", kind: "customer", stage: "shipped", label: bi("Nebius · Vera Rubin racks running", "Nebius · Vera Rubin 机架已运行"), status: bi("Running per NVIDIA", "英伟达称已运行"), summary: bi("Nebius, a neocloud, is named in NVIDIA's Q2 FY2027 results among partners with Vera Rubin racks running.", "新型云服务商 Nebius 被英伟达 2027 财年第二季度业绩列为已运行 Vera Rubin 机架的合作伙伴。"), limit: bi("The release does not disclose Nebius's volume or when customers can rent the capacity.", "该公告未披露 Nebius 的规模，也未说明客户何时可租用这些算力。"), ...Q2_FY27 },
  { id: "amzn-rubin", companyId: "US:AMZN", symbol: "AMZN", edge: "US:AMZN__PLANNED_ADOPTER_OF__US:NVDA", layer: "cloud", kind: "customer", stage: "announced", label: bi("AWS · Planned Vera Rubin cloud provider", "AWS · 计划提供 Vera Rubin 云服务"), status: bi("Planned in cited announcement", "所引公告为计划"), summary: bi("NVIDIA named AWS among the first cloud providers to deploy Vera Rubin-based instances in 2026, and among cloud providers ramping Vera Rubin.", "英伟达将 AWS 列为 2026 年首批部署 Vera Rubin 实例的云服务商之一，并列入推进 Vera Rubin 的云服务商。"), limit: bi("AWS is not in NVIDIA's Q2 FY2027 list of partners with racks running. Look for an AWS instance launch before treating this as deployed.", "AWS 不在英伟达 2027 财年第二季度“机架已运行”的名单中；在视为已部署前，应等待 AWS 发布实例。"), ...RUBIN_PRODUCTION, also: [RUBIN_CES] },
  { id: "openai-loi", companyId: "ORG:OPENAI", symbol: null, edge: null, layer: "cloud", kind: "customer", stage: "announced", label: bi("OpenAI · 10 GW letter of intent", "OpenAI · 10 GW 意向书"), status: bi("Letter of intent", "意向书"), summary: bi("OpenAI and NVIDIA announced a letter of intent to deploy at least 10 GW of NVIDIA systems, with the first gigawatt planned on Vera Rubin in the second half of 2026. NVIDIA said it intends to invest up to $100 billion as each gigawatt is deployed.", "OpenAI 与英伟达宣布意向书，计划部署至少 10 GW 英伟达系统，首个 1 GW 计划于 2026 年下半年基于 Vera Rubin 部署；英伟达表示拟随每 GW 部署逐步投资最多 1000 亿美元。"), limit: bi("A letter of intent is not a purchase agreement. Later press coverage describes changed investment terms; this page has not confirmed them in a primary source.", "意向书不是采购协议。后续媒体报道称投资条款有变化，本页尚未在原始来源中确认。"), source: "OpenAI–NVIDIA announcement", url: "https://nvidianews.nvidia.com/news/openai-and-nvidia-announce-strategic-partnership-to-deploy-10gw-of-nvidia-systems", date: "2025-09-22" },
  { id: "anthropic-compute", companyId: "ORG:ANTHROPIC", symbol: null, edge: null, layer: "cloud", kind: "customer", stage: "announced", label: bi("Anthropic · Up to 1 GW on Grace Blackwell and Vera Rubin", "Anthropic · 最多 1 GW Grace Blackwell 与 Vera Rubin"), status: bi("Commitment announced", "已宣布承诺"), summary: bi("Anthropic said its compute commitment will initially be up to one gigawatt with NVIDIA Grace Blackwell and Vera Rubin systems, alongside a $30 billion Azure compute commitment. The companies also announced a technology partnership, and NVIDIA committed to invest up to $10 billion in Anthropic.", "Anthropic 表示其算力承诺初期为最多 1 GW 的英伟达 Grace Blackwell 与 Vera Rubin 系统，同时承诺采购 300 亿美元 Azure 算力；双方同时宣布技术合作，英伟达承诺向 Anthropic 投资最多 100 亿美元。"), limit: bi("\"Up to\" sets a ceiling, not a delivered amount. The announcement does not say Anthropic buys directly from NVIDIA; capacity may reach it through cloud providers.", "“最多”是上限而非已交付量；公告未说明 Anthropic 直接向英伟达采购，算力可能经由云服务商提供。"), source: "Microsoft, NVIDIA and Anthropic announcement", url: "https://www.anthropic.com/news/microsoft-nvidia-anthropic-announce-strategic-partnerships", date: "2025-11-18" },
];

export type LayerSummary = Evidence & { also?: Evidence[]; layer: Layer; stage: Stage; position: Bilingual };
export const layerSummaries: LayerSummary[] = [
  { layer: "chips", stage: "shipped", position: bi("NVIDIA is fabless. It designs GPUs and Arm-based CPUs (Grace, now Vera) and relies on foundries, memory suppliers and contract manufacturers for every manufacturing step.", "英伟达采用无晶圆厂模式，设计 GPU 与基于 Arm 的 CPU（Grace，现为 Vera），制造各环节依赖代工厂、内存供应商和合约制造商。"), ...TEN_K },
  { layer: "networking", stage: "shipped", position: bi("NVLink interconnects and switches, and end-to-end InfiniBand and Ethernet platforms: network adapters, cables, DPUs, switch chips and systems, plus software. NVIDIA reports networking inside its Compute & Networking segment, whose revenue grew 18% from the prior quarter and 114% from a year earlier in Q2 FY2027.", "NVLink 互连与交换机，以及端到端的 InfiniBand 与以太网平台：网卡、线缆、DPU、交换芯片与系统及软件。英伟达将网络业务计入“计算与网络”分部，该分部 2027 财年第二季度收入环比增长 18%、同比增长 114%。"), ...TEN_K, also: [CFO_Q2_FY27] },
  { layer: "systems", stage: "shipped", position: bi("Data center products are typically delivered as rack-scale systems, subsystems or modules. OEMs and ODMs such as Dell, HPE, Supermicro, Foxconn and Wistron build the racks customers receive.", "数据中心产品通常以机架级系统、子系统或模块交付；戴尔、慧与、超微、富士康和纬创等 OEM/ODM 制造客户收到的机架。"), ...TEN_K, also: [RUBIN_PRODUCTION] },
  { layer: "software", stage: "shipped", position: bi("CUDA runs on all NVIDIA GPUs and sits beneath hundreds of domain-specific libraries, frameworks and SDKs. NVIDIA describes its developer base and installed base as strengthening the ecosystem.", "CUDA 运行于所有英伟达 GPU 之上，其上是数百个领域专用库、框架与 SDK；英伟达认为其开发者和装机基础增强了生态。"), ...TEN_K },
  { layer: "cloud", stage: "shipped", position: bi("Data center revenue was $89.0 billion in Q2 FY2027 (quarter ended July 26, 2026), up 117% from a year earlier. Most GPUs reach end users through hyperscalers, neoclouds and model labs, often indirectly via OEMs and ODMs.", "2027 财年第二季度（截至 2026 年 7 月 26 日）数据中心收入为 890 亿美元，同比增长 117%。多数 GPU 通过超大规模云、新型云服务商和模型公司触达最终用户，常经由 OEM/ODM 间接销售。"), ...Q2_FY27 },
];

export type RoadmapItem = Evidence & { also?: Evidence[]; name: string; stage: Stage; status: Bilingual; summary: Bilingual };
export const roadmap: RoadmapItem[] = [
  { name: "Blackwell", stage: "shipped", status: bi("Shipping in volume", "已批量出货"), summary: bi("Blackwell reached volume production; NVIDIA marked the first Blackwell wafer produced at TSMC Arizona.", "Blackwell 已进入量产；英伟达庆祝台积电亚利桑那工厂生产的首片 Blackwell 晶圆。"), source: "NVIDIA blog: first US Blackwell wafer", url: "https://blogs.nvidia.com/blog/tsmc-blackwell-manufacturing/", date: "2025-10-17" },
  { name: "Blackwell Ultra (GB300)", stage: "shipped", status: bi("Shipping; NVIDIA cites its ramp for Q2 FY2027 growth", "已出货；英伟达称其放量推动 2027 财年第二季度增长"), summary: bi("Announced at GTC in March 2025 for the second half of 2025. The first GB300 NVL72 reached CoreWeave in July 2025, and NVIDIA attributes Q2 FY2027 data center growth to the Blackwell Ultra ramp.", "2025 年 3 月 GTC 宣布，计划 2025 年下半年推出；首台 GB300 NVL72 于 2025 年 7 月交付 CoreWeave，英伟达将 2027 财年第二季度数据中心增长归因于 Blackwell Ultra 放量。"), source: "NVIDIA Blackwell Ultra announcement", url: "https://nvidianews.nvidia.com/news/nvidia-blackwell-ultra-ai-factory-platform-paves-way-for-age-of-ai-reasoning", date: "2025-03-18", also: [CRWV_GB300, CFO_Q2_FY27] },
  { name: "Vera Rubin", stage: "announced", status: bi("Ramping; first racks delivered, broad shipments from fall 2026", "放量中；首批机架已交付，2026 年秋季起广泛出货"), summary: bi("Six chips (Vera CPU, Rubin GPU, NVLink 6 Switch, ConnectX-9, BlueField-4, Spectrum-6) announced in January 2026. NVIDIA said production shipments begin in fall 2026. Early racks are already running at CoreWeave and several clouds.", "2026 年 1 月发布六款芯片（Vera CPU、Rubin GPU、NVLink 6 交换芯片、ConnectX-9、BlueField-4、Spectrum-6）；英伟达称量产出货于 2026 年秋季开始，早期机架已在 CoreWeave 和多家云厂商运行。"), ...RUBIN_PRODUCTION, also: [RUBIN_CES, CRWV_RUBIN_FIRST, Q2_FY27] },
];

export function researchFilters(layer?: string, kind?: string, stage?: string) {
  return {
    layer: (LAYERS as readonly string[]).includes(layer ?? "") ? layer! : "all",
    kind: (RELATIONS as readonly string[]).includes(kind ?? "") ? kind! : "all",
    stage: (STAGES as readonly string[]).includes(stage ?? "") ? stage! : "all",
  };
}
export function selectedConnections(layer: string, kind: string, stage = "all") {
  return researchConnections.filter(row => (layer === "all" || row.layer === layer) && (kind === "all" || row.kind === kind) && (stage === "all" || row.stage === stage));
}
