// Curated industry roles, not commercial edges or a complete market directory.
// Full 2026 interim reports verified 2026-09-10; Sina links reproduce issuer filings.
export const chinaSupplyChain = [
  { id: "XSHG:688041", name: "海光信息", en: "Hygon Information", stage: "算力芯片", stageEn: "Compute chips", description: "研发通用处理器（CPU）和协处理器（DCU），面向服务器与数据中心计算。", descriptionEn: "Develops CPUs and DCUs for server and data-center computing.", source: "https://vip.stock.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12492765", sourceLabel: "2026 年半年度报告", sourceLabelEn: "2026 interim report" },
  { id: "XSHG:688008", name: "澜起科技", en: "Montage Technology", stage: "内存与高速互连", stageEn: "Memory interconnects", description: "提供内存接口及高速互连芯片，产品包括 DDR5 内存接口芯片、PCIe Retimer 和 CXL 相关芯片。", descriptionEn: "Provides memory-interface and high-speed interconnect chips, including DDR5 interfaces, PCIe retimers and CXL products.", source: "https://vip.stock.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12570414&stockid=688008", sourceLabel: "2026 年半年度报告", sourceLabelEn: "2026 interim report" },
  { id: "XSHG:601138", name: "工业富联", en: "Foxconn Industrial Internet", stage: "服务器与系统", stageEn: "Servers and systems", description: "业务涵盖 AI 服务器、机柜级系统和高速网络设备，服务数据中心算力基础设施。", descriptionEn: "Builds AI servers, rack-scale systems and high-speed networking equipment for data-center infrastructure.", source: "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12487983&stockid=601138", sourceLabel: "2026 年半年度报告", sourceLabelEn: "2026 interim report" },
  { id: "XSHE:300308", name: "中际旭创", en: "Zhongji Innolight", stage: "光通信", stageEn: "Optical networking", description: "提供数据中心与 AI 互连光模块，产品系列覆盖 100G 至 1.6T。", descriptionEn: "Offers optical transceivers for data centers and AI interconnects, with product families from 100G to 1.6T.", source: "https://static.cninfo.com.cn/finalpage/2026-08-22/1225491753.PDF", sourceLabel: "2026 年半年度报告", sourceLabelEn: "2026 interim report" },
  { id: "XSHE:002837", name: "英维克", en: "Envicool", stage: "散热与液冷", stageEn: "Cooling", description: "提供精密温控和液冷产品，应用于数据中心、AI 算力等场景。", descriptionEn: "Provides precision thermal management and liquid-cooling products for data centers and AI computing.", source: "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12525843&stockid=002837", sourceLabel: "2026 年半年度报告", sourceLabelEn: "2026 interim report" },
] as const;
